/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.encoming.presentation;

/**
 *
 * @author juanmanuelmartinezromero
 */
public class PPrincipal extends javax.swing.JPanel {

    private principal principal;

    /**
     * Creates new form PPrincipal
     */
    public PPrincipal(principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bInscribirEstudiante = new javax.swing.JButton();
        bIngresarEstudiante = new javax.swing.JButton();
        bInscribirCursos = new javax.swing.JButton();
        bInscritosPorCurso = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("PARCIAL FINAL");

        bInscribirEstudiante.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bInscribirEstudiante.setText("Inscribir un Estudiante a un Curso");
        bInscribirEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInscribirEstudianteActionPerformed(evt);
            }
        });

        bIngresarEstudiante.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bIngresarEstudiante.setText("Crear Estudiante");
        bIngresarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarEstudianteActionPerformed(evt);
            }
        });

        bInscribirCursos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bInscribirCursos.setText("Crear Curso");
        bInscribirCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInscribirCursosActionPerformed(evt);
            }
        });

        bInscritosPorCurso.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bInscritosPorCurso.setText("Ver Inscritos por Curso");
        bInscritosPorCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInscritosPorCursoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(0, 13, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, bInscribirEstudiante, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, bIngresarEstudiante, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, bInscribirCursos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, bInscritosPorCurso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bInscribirCursos)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bIngresarEstudiante)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bInscribirEstudiante)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bInscritosPorCurso)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bInscribirCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInscribirCursosActionPerformed
        principal.cambiarPanel(new createsCourses(principal));
    }//GEN-LAST:event_bInscribirCursosActionPerformed

    private void bIngresarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarEstudianteActionPerformed
        principal.cambiarPanel(new createStudents(principal));
    }//GEN-LAST:event_bIngresarEstudianteActionPerformed

    private void bInscribirEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInscribirEstudianteActionPerformed
        principal.cambiarPanel(new enrollStudent(principal));
    }//GEN-LAST:event_bInscribirEstudianteActionPerformed

    private void bInscritosPorCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInscritosPorCursoActionPerformed
        principal.cambiarPanel(new InscritosPorCurso(principal));
    }//GEN-LAST:event_bInscritosPorCursoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresarEstudiante;
    private javax.swing.JButton bInscribirCursos;
    private javax.swing.JButton bInscribirEstudiante;
    private javax.swing.JButton bInscritosPorCurso;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
