/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.encoming.presentation;

import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author juanmanuelmartinezromero
 */
public class PPrincipal extends javax.swing.JPanel {

    private principal principal;

    /**
     * Creates new form PPrincipal
     */
    public PPrincipal(principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bInscribirEstudiante = new javax.swing.JButton();
        bIngresarEstudiante = new javax.swing.JButton();
        bInscribirCursos = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("PARCIAL FINAL");

        bInscribirEstudiante.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        bInscribirEstudiante.setText("Inscribir Un Estudiante");

        bIngresarEstudiante.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        bIngresarEstudiante.setText("Ingresar Estudiante");
        bIngresarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarEstudianteActionPerformed(evt);
            }
        });

        bInscribirCursos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        bInscribirCursos.setText("Inscribir Curso");
        bInscribirCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInscribirCursosActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(bIngresarEstudiante, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(bInscribirCursos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(bInscribirEstudiante)
                            .add(jLabel1))
                        .add(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bInscribirEstudiante)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bIngresarEstudiante)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bInscribirCursos))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bInscribirCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInscribirCursosActionPerformed
        principal.cambiarPanel(new createsCourses(principal));
    }//GEN-LAST:event_bInscribirCursosActionPerformed

    private void bIngresarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarEstudianteActionPerformed
        principal.cambiarPanel(new createStudents(principal));
    }//GEN-LAST:event_bIngresarEstudianteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresarEstudiante;
    private javax.swing.JButton bInscribirCursos;
    private javax.swing.JButton bInscribirEstudiante;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
