package com.encoming.encoming.test;

import javax.script.Invocable;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

public class Main {

    public static void main(String[] args) throws ScriptException, NoSuchMethodException {
        ScriptEngineManager script = new ScriptEngineManager();
        ScriptEngine js = script.getEngineByName("JavaScript");
        js.setContext(null);
        // Añanidimos al string codigo JavaScript
        String codigo = "function GScript(src) {\n"
                + "    document.write('<' + 'script src=\"' + src + '\"' +' type=\"text/javascript\"><' + '/script>');\n"
                + "}\n"
                + "function GBrowserIsCompatible() {\n"
                + "    return true;\n"
                + "}\n"
                + "function GApiInit() {\n"
                + "    if (GApiInit.called) return;\n"
                + "    GApiInit.called = true;\n"
                + "    window.GAddMessages && GAddMessages({\n"
                + "        160: '\\x3cH1\\x3eError del servidor\\x3c/H1\\x3eError temporal del servidor. No se pudo completar tu solicitud. \\x3cp\\x3ePor favor, vuélvelo a intentar dentro de un minuto aproximadamente.\\x3c/p\\x3e',\n"
                + "        1415: '.',\n"
                + "        1416: ',',\n"
                + "        1547: 'mi',\n"
                + "        1616: 'km',\n"
                + "        4100: 'm',\n"
                + "        4101: 'pies',\n"
                + "        10018: 'Cargando...',\n"
                + "        10021: 'Aumentar',\n"
                + "        10022: 'Reducir',\n"
                + "        10024: 'Arrastra para ampliar o reducir',\n"
                + "        10029: 'Volver al último resultado',\n"
                + "        10049: 'Mapa',\n"
                + "        10050: 'Satélite',\n"
                + "        10093: 'Términos de uso',\n"
                + "        10111: 'Mapa',\n"
                + "        10112: 'Sat.',\n"
                + "        10116: 'Híbrido',\n"
                + "        10117: 'Híb.',\n"
                + "        10120: 'Lo lamentamos, pero no disponemos de mapas de esta región con este nivel de zoom.\\x3cp\\x3ePrueba a reducir el zoom para tener una perspectiva más amplia.\\x3c/p\\x3e',\n"
                + "        10121: 'Lo lamentamos, pero no disponemos de imágenes de esta región con este nivel de zoom.\\x3cp\\x3ePrueba a reducir el zoom para tener una perspectiva más amplia.\\x3c/p\\x3e',\n"
                + "        10507: 'Vista panorámica a la izquierda',\n"
                + "        10508: 'Vista panorámica a la derecha',\n"
                + "        10509: 'Vista panorámica hacia arriba',\n"
                + "        10510: 'Vista panorámica hacia abajo',\n"
                + "        10511: 'Mostrar callejero',\n"
                + "        10512: 'Mostrar imágenes por satélite',\n"
                + "        10513: 'Mostrar imágenes con nombres de calle',\n"
                + "        10806: 'Haz clic para visualizar esta zona en Google Maps',\n"
                + "        10807: 'Tráfico',\n"
                + "        10808: 'Mostrar tráfico',\n"
                + "        10809: 'Ocultar tráfico',\n"
                + "        12150: '%1$s en %2$s',\n"
                + "        12151: '%1$s en %2$s a la altura de %3$s',\n"
                + "        12152: '%1$s en %2$s entre %3$s y %4$s',\n"
                + "        10985: 'Ampliar',\n"
                + "        10986: 'Reducir',\n"
                + "        11047: 'Centrar el mapa aquí',\n"
                + "        11089: '\\x3ca href\\x3d\\x22javascript:void(0);\\x22\\x3eAcercar\\x3c/a\\x3e para ver el tráfico de esta zona',\n"
                + "        11259: 'Pantalla completa',\n"
                + "        11751: 'Mostrar callejero con relieve',\n"
                + "        11752: 'Estilo:',\n"
                + "        11757: 'Cambiar estilo del mapa',\n"
                + "        11758: 'Relieve',\n"
                + "        11759: 'Terr.',\n"
                + "        11794: 'Superponer callejero',\n"
                + "        11303: 'Ayuda de Street View',\n"
                + "        11274: 'Para usar Street View necesitas Adobe Flash Player, versión %1$d o posterior.',\n"
                + "        11382: 'Consigue la última versión de Flash Player.',\n"
                + "        11314: 'Disculpa las molestias. Street View no está disponible en este momento debido a que el sistema experimenta una gran demanda.\\x3cbr\\x3eInténtalo de nuevo más tarde.',\n"
                + "        1559: 'N',\n"
                + "        1560: 'S',\n"
                + "        1561: 'O',\n"
                + "        1562: 'E',\n"
                + "        1608: 'NO',\n"
                + "        1591: 'NE',\n"
                + "        1605: 'SO',\n"
                + "        1606: 'SE',\n"
                + "        11907: 'Esta imagen ya no está disponible',\n"
                + "        10041: 'Ayuda',\n"
                + "        12471: 'Ubicación actual',\n"
                + "        12492: 'Earth',\n"
                + "        12823: 'Google ha deshabilitado el uso del API de Google Maps para esta aplicación. Para obtener más información, consulta las Condiciones del servicio: %1$s.',\n"
                + "        12822: 'http://code.google.com/apis/maps/terms.html',\n"
                + "        12915: 'Mejorar el mapa',\n"
                + "        12916: 'Google, Europa Technologies',\n"
                + "        13171: 'Híbrido 3D',\n"
                + "        0: ''\n"
                + "    });\n"
                + "}\n"
                + "var GLoad;\n"
                + "(function() {\n"
                + "    GLoad = function(apiCallback) {\n"
                + "        var callee = arguments.callee;\n"
                + "        GApiInit();\n"
                + "        var opts = {\n"
                + "            export_legacy_names:true,\n"
                + "            tile_override:[{\n"
                + "                maptype:0,\n"
                + "                min_zoom:\"7\",\n"
                + "                max_zoom:\"7\",\n"
                + "                rect:[{\n"
                + "                    lo:{\n"
                + "                        lat_e7:330000000,\n"
                + "                        lng_e7:1246050000\n"
                + "                    },\n"
                + "                    hi:{\n"
                + "                        lat_e7:386200000,\n"
                + "                        lng_e7:1293600000\n"
                + "                    }\n"
                + "                },{\n"
                + "                lo:{\n"
                + "                    lat_e7:366500000,\n"
                + "                    lng_e7:1297000000\n"
                + "                },\n"
                + "                hi:{\n"
                + "                    lat_e7:386200000,\n"
                + "                    lng_e7:1314843700\n"
                + "                }\n"
                + "            }],\n"
                + "        uris:[\"http://mt0.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt1.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt2.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt3.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\"]\n"
                + "        },{\n"
                + "        maptype:0,\n"
                + "        min_zoom:\"8\",\n"
                + "        max_zoom:\"8\",\n"
                + "        rect:[{\n"
                + "            lo:{\n"
                + "                lat_e7:330000000,\n"
                + "                lng_e7:1246050000\n"
                + "            },\n"
                + "            hi:{\n"
                + "                lat_e7:386200000,\n"
                + "                lng_e7:1279600000\n"
                + "            }\n"
                + "        },{\n"
                + "        lo:{\n"
                + "            lat_e7:345000000,\n"
                + "            lng_e7:1279600000\n"
                + "        },\n"
                + "        hi:{\n"
                + "            lat_e7:386200000,\n"
                + "            lng_e7:1286700000\n"
                + "        }\n"
                + "    },{\n"
                + "    lo:{\n"
                + "        lat_e7:354690000,\n"
                + "        lng_e7:1286700000\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386200000,\n"
                + "        lng_e7:1314843700\n"
                + "    }\n"
                + "}],\n"
                + "uris:[\"http://mt0.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt1.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt2.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt3.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\"]\n"
                + "},{\n"
                + "    maptype:0,\n"
                + "    min_zoom:\"9\",\n"
                + "    max_zoom:\"9\",\n"
                + "    rect:[{\n"
                + "        lo:{\n"
                + "            lat_e7:330000000,\n"
                + "            lng_e7:1246050000\n"
                + "        },\n"
                + "        hi:{\n"
                + "            lat_e7:386200000,\n"
                + "            lng_e7:1279600000\n"
                + "        }\n"
                + "    },{\n"
                + "    lo:{\n"
                + "        lat_e7:340000000,\n"
                + "        lng_e7:1279600000\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386200000,\n"
                + "        lng_e7:1286700000\n"
                + "    }\n"
                + "},{\n"
                + "    lo:{\n"
                + "        lat_e7:348900000,\n"
                + "        lng_e7:1286700000\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386200000,\n"
                + "        lng_e7:1302000000\n"
                + "    }\n"
                + "},{\n"
                + "    lo:{\n"
                + "        lat_e7:368300000,\n"
                + "        lng_e7:1302000000\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386200000,\n"
                + "        lng_e7:1314843700\n"
                + "    }\n"
                + "}],\n"
                + "uris:[\"http://mt0.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt1.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt2.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt3.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\"]\n"
                + "},{\n"
                + "    maptype:0,\n"
                + "    min_zoom:\"10\",\n"
                + "    max_zoom:\"19\",\n"
                + "    rect:[{\n"
                + "        lo:{\n"
                + "            lat_e7:329890840,\n"
                + "            lng_e7:1246055600\n"
                + "        },\n"
                + "        hi:{\n"
                + "            lat_e7:386930130,\n"
                + "            lng_e7:1284960940\n"
                + "        }\n"
                + "    },{\n"
                + "    lo:{\n"
                + "        lat_e7:344646740,\n"
                + "        lng_e7:1284960940\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386930130,\n"
                + "        lng_e7:1288476560\n"
                + "    }\n"
                + "},{\n"
                + "    lo:{\n"
                + "        lat_e7:350277470,\n"
                + "        lng_e7:1288476560\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386930130,\n"
                + "        lng_e7:1310531620\n"
                + "    }\n"
                + "},{\n"
                + "    lo:{\n"
                + "        lat_e7:370277730,\n"
                + "        lng_e7:1310531620\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386930130,\n"
                + "        lng_e7:1314843700\n"
                + "    }\n"
                + "}],\n"
                + "uris:[\"http://mt0.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt1.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt2.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\",\"http://mt3.gmaptiles.co.kr/mt/v=kr1.17\\x26hl=es\\x26src=api\\x26\"]\n"
                + "},{\n"
                + "    maptype:3,\n"
                + "    min_zoom:\"7\",\n"
                + "    max_zoom:\"7\",\n"
                + "    rect:[{\n"
                + "        lo:{\n"
                + "            lat_e7:330000000,\n"
                + "            lng_e7:1246050000\n"
                + "        },\n"
                + "        hi:{\n"
                + "            lat_e7:386200000,\n"
                + "            lng_e7:1293600000\n"
                + "        }\n"
                + "    },{\n"
                + "    lo:{\n"
                + "        lat_e7:366500000,\n"
                + "        lng_e7:1297000000\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386200000,\n"
                + "        lng_e7:1314843700\n"
                + "    }\n"
                + "}],\n"
                + "uris:[\"http://mt0.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt1.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt2.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt3.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\"]\n"
                + "},{\n"
                + "    maptype:3,\n"
                + "    min_zoom:\"8\",\n"
                + "    max_zoom:\"8\",\n"
                + "    rect:[{\n"
                + "        lo:{\n"
                + "            lat_e7:330000000,\n"
                + "            lng_e7:1246050000\n"
                + "        },\n"
                + "        hi:{\n"
                + "            lat_e7:386200000,\n"
                + "            lng_e7:1279600000\n"
                + "        }\n"
                + "    },{\n"
                + "    lo:{\n"
                + "        lat_e7:345000000,\n"
                + "        lng_e7:1279600000\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386200000,\n"
                + "        lng_e7:1286700000\n"
                + "    }\n"
                + "},{\n"
                + "    lo:{\n"
                + "        lat_e7:354690000,\n"
                + "        lng_e7:1286700000\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386200000,\n"
                + "        lng_e7:1314843700\n"
                + "    }\n"
                + "}],\n"
                + "uris:[\"http://mt0.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt1.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt2.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt3.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\"]\n"
                + "},{\n"
                + "    maptype:3,\n"
                + "    min_zoom:\"9\",\n"
                + "    max_zoom:\"9\",\n"
                + "    rect:[{\n"
                + "        lo:{\n"
                + "            lat_e7:330000000,\n"
                + "            lng_e7:1246050000\n"
                + "        },\n"
                + "        hi:{\n"
                + "            lat_e7:386200000,\n"
                + "            lng_e7:1279600000\n"
                + "        }\n"
                + "    },{\n"
                + "    lo:{\n"
                + "        lat_e7:340000000,\n"
                + "        lng_e7:1279600000\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386200000,\n"
                + "        lng_e7:1286700000\n"
                + "    }\n"
                + "},{\n"
                + "    lo:{\n"
                + "        lat_e7:348900000,\n"
                + "        lng_e7:1286700000\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386200000,\n"
                + "        lng_e7:1302000000\n"
                + "    }\n"
                + "},{\n"
                + "    lo:{\n"
                + "        lat_e7:368300000,\n"
                + "        lng_e7:1302000000\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386200000,\n"
                + "        lng_e7:1314843700\n"
                + "    }\n"
                + "}],\n"
                + "uris:[\"http://mt0.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt1.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt2.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt3.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\"]\n"
                + "},{\n"
                + "    maptype:3,\n"
                + "    min_zoom:\"10\",\n"
                + "    rect:[{\n"
                + "        lo:{\n"
                + "            lat_e7:329890840,\n"
                + "            lng_e7:1246055600\n"
                + "        },\n"
                + "        hi:{\n"
                + "            lat_e7:386930130,\n"
                + "            lng_e7:1284960940\n"
                + "        }\n"
                + "    },{\n"
                + "    lo:{\n"
                + "        lat_e7:344646740,\n"
                + "        lng_e7:1284960940\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386930130,\n"
                + "        lng_e7:1288476560\n"
                + "    }\n"
                + "},{\n"
                + "    lo:{\n"
                + "        lat_e7:350277470,\n"
                + "        lng_e7:1288476560\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386930130,\n"
                + "        lng_e7:1310531620\n"
                + "    }\n"
                + "},{\n"
                + "    lo:{\n"
                + "        lat_e7:370277730,\n"
                + "        lng_e7:1310531620\n"
                + "    },\n"
                + "    hi:{\n"
                + "        lat_e7:386930130,\n"
                + "        lng_e7:1314843700\n"
                + "    }\n"
                + "}],\n"
                + "uris:[\"http://mt0.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt1.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt2.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\",\"http://mt3.gmaptiles.co.kr/mt/v=kr1p.17\\x26hl=es\\x26src=api\\x26\"]\n"
                + "}],\n"
                + "jsmain:\"http://maps.gstatic.com/intl/es_ALL/mapfiles/400d/maps2.api/main.js\",\n"
                + "bcp47_language_code:\"es\",\n"
                + "obliques_urls:[\"http://khm0.googleapis.com/kh?v=65\\x26src=app\\x26\",\"http://khm1.googleapis.com/kh?v=65\\x26src=app\\x26\"],\n"
                + "token:\"3557517872\",\n"
                + "jsmodule_base_url:\"http://maps.gstatic.com/intl/es_ALL/mapfiles/400d/maps2.api\",\n"
                + "generic_tile_urls:[\"http://mt0.googleapis.com/vt?hl=es\\x26src=api\\x26\",\"http://mt1.googleapis.com/vt?hl=es\\x26src=api\\x26\"],\n"
                + "ignore_auth:false,\n"
                + "sv_host:\"http://cbk0.google.com\"\n"
                + "};\n"
                + "\n"
                + "apiCallback([\"http://mt0.googleapis.com/vt/lyrs\\x3dm@196000000\\x26hl\\x3des\\x26src\\x3dapi\\x26\",\"http://mt1.googleapis.com/vt/lyrs\\x3dm@196000000\\x26hl\\x3des\\x26src\\x3dapi\\x26\"], [\"http://khm0.googleapis.com/kh/v\\x3d121\\x26src\\x3dapp\\x26\",\"http://khm1.googleapis.com/kh/v\\x3d121\\x26src\\x3dapp\\x26\"], [\"http://mt0.googleapis.com/vt/lyrs\\x3dh@196000000\\x26hl\\x3des\\x26src\\x3dapi\\x26\",\"http://mt1.googleapis.com/vt/lyrs\\x3dh@196000000\\x26hl\\x3des\\x26src\\x3dapi\\x26\"],\"\"  ,\"\"  ,\"\"  ,true,\"google.maps.\",opts,[\"http://mt0.googleapis.com/vt/lyrs\\x3dt@129,r@196000000\\x26hl\\x3des\\x26src\\x3dapi\\x26\",\"http://mt1.googleapis.com/vt/lyrs\\x3dt@129,r@196000000\\x26hl\\x3des\\x26src\\x3dapi\\x26\"]);\n"
                + "if (!callee.called) {\n"
                + "    callee.called = true;\n"
                + "}\n"
                + "}\n"
                + "})();\n"
                + "function GUnload() {\n"
                + "    if (window.GUnloadApi) {\n"
                + "        GUnloadApi();\n"
                + "    }\n"
                + "}\n"
                + "var _mIsRtl = false;\n"
                + "var _mHost = \"http://maps.google.com\";\n"
                + "var _mUri = \"/maps\";\n"
                + "var _mDomain = \"google.com\";\n"
                + "var _mStaticPath = \"http://maps.gstatic.com/intl/es_ALL/mapfiles/\";\n"
                + "var _mJavascriptVersion = G_API_VERSION = \"400d\";\n"
                + "var _mTermsUrl = \"http://www.google.com/intl/es_ALL/help/terms_maps.html\";\n"
                + "var _mLocalSearchUrl = \"http://www.google.com/uds/solutions/localsearch/gmlocalsearch.js\";\n"
                + "var _mHL = \"es\";\n"
                + "var _mGL = \"\";\n"
                + "var _mTrafficEnableApi = true;\n"
                + "var _mTrafficTileServerUrls = [\"http://mt0.google.com/mapstt\",\"http://mt1.google.com/mapstt\",\"http://mt2.google.com/mapstt\",\"http://mt3.google.com/mapstt\"];\n"
                + "var _mCityblockLatestFlashUrl = \"http://maps.google.com/local_url?dq=&amp;q=http://www.adobe.com/shockwave/download/download.cgi%3FP1_Prod_Version%3DShockwaveFlash&amp;s=ANYYN7lCgR1J0Lu7tVcPbijNF_TKW5wcqQ\";\n"
                + "var _mCityblockFrogLogUsage = false;\n"
                + "var _mCityblockInfowindowLogUsage = false;\n"
                + "var _mCityblockUseSsl = false;\n"
                + "var _mSatelliteToken = \"fzwq1BtIu22OvJHtu3YUyPljUXqJchkNVK3Hlw\";\n"
                + "var _mMapCopy = \"Datos de mapa \\x26#169;2012\";\n"
                + "var _mSatelliteCopy = \"Imágenes \\x26#169;2012\";\n"
                + "var _mGoogleCopy = \"\\x26#169;2012 Google\";\n"
                + "var _mPreferMetric = false;\n"
                + "var _mDirectionsEnableApi = true;\n"
                + "var _mLayersTileBaseUrls = ['http://mt0.google.com/mapslt','http://mt1.google.com/mapslt','http://mt2.google.com/mapslt','http://mt3.google.com/mapslt'];\n"
                + "var _mLayersFeaturesBaseUrl = \"http://mt0.google.com/vt/ft\";\n"
                + "function GLoadMapsScript() {\n"
                + "    if (!GLoadMapsScript.called && GBrowserIsCompatible()) {\n"
                + "        GLoadMapsScript.called = true;\n"
                + "        GScript(\"http://maps.gstatic.com/intl/es_ALL/mapfiles/400d/maps2.api/main.js\");\n"
                + "    }\n"
                + "}(function() {\n"
                + "    if (!window.google) window.google = {};\n"
                + "        \n"
                + "    if (!window.google.maps) window.google.maps = {};\n"
                + "        \n"
                + "    var ns = window.google.maps;\n"
                + "    ns.BrowserIsCompatible = GBrowserIsCompatible;\n"
                + "    ns.Unload = GUnload;\n"
                + "})();\n"
                + "\n"
                + "function getRoute(from, to) {\n"
                + "                            var gdir=new GDirections();\n"
                + "                            gdir.load(\"from: \"+from+\" to: \"+to,\n"
                + "                            { \"locale\": \"es\", \"travelMode\" : G_TRAVEL_MODE_DRIVING });\n"
                + "                            var drivingDistanceKilometers = gdir.getDistance().meters / 1000;\n"
                + "                            return drivingDistanceKilometers;\n"
                + "                        }\n"
                + "                        \n"
                + "GLoadMapsScript();";
        js.eval(codigo);
        Invocable inv = (Invocable) js;
        System.out.println(inv.invokeFunction("getRoute", "Bogotá, Colombia", "Medellín, Colombia"));
    }
}